create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.printers (
  id uuid primary key default gen_random_uuid(),
  printer_code integer generated by default as identity unique not null,
  name text not null,
  serial_number text,
  ip_address text,
  mac_address text,
  supplier text,
  manufacturer text,
  model text,
  department_id uuid references public.departments(id) on delete set null,
  location_id uuid references public.locations(id) on delete set null,
  primary_contact_id uuid references public.contacts(id) on delete set null,
  status text not null default 'Active' check (status in ('Active', 'Needs Attention', 'Offline', 'Retired')),
  toner_status text not null default 'OK' check (toner_status in ('OK', 'Low', 'Critical', 'Out', 'Ordered')),
  paper_status text not null default 'OK' check (paper_status in ('OK', 'Low', 'Critical', 'Out', 'Ordered')),
  toner_model text,
  paper_size text,
  last_meter_reading integer,
  last_meter_reading_at date,
  warranty_end_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists public.printer_toner_orders (
  id uuid primary key default gen_random_uuid(),
  printer_id uuid not null references public.printers(id) on delete cascade,
  requested_by_contact_id uuid references public.contacts(id) on delete set null,
  toner_type text not null,
  quantity integer not null default 1 check (quantity > 0),
  status text not null default 'Requested' check (status in ('Requested', 'Ordered', 'Backordered', 'Received', 'Cancelled')),
  supplier text,
  order_number text,
  requested_at date not null default current_date,
  expected_at date,
  received_at date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.printer_paper_orders (
  id uuid primary key default gen_random_uuid(),
  printer_id uuid not null references public.printers(id) on delete cascade,
  requested_by_contact_id uuid references public.contacts(id) on delete set null,
  paper_size text not null,
  reams integer not null default 1 check (reams > 0),
  status text not null default 'Requested' check (status in ('Requested', 'Ordered', 'Backordered', 'Received', 'Cancelled')),
  supplier text,
  order_number text,
  requested_at date not null default current_date,
  expected_at date,
  received_at date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.printer_tickets (
  id uuid primary key default gen_random_uuid(),
  printer_id uuid not null references public.printers(id) on delete cascade,
  logged_by_contact_id uuid references public.contacts(id) on delete set null,
  title text not null,
  description text,
  priority text not null default 'Normal' check (priority in ('Low', 'Normal', 'High', 'Urgent')),
  status text not null default 'Open' check (status in ('Open', 'In Progress', 'Waiting Supplier', 'Resolved', 'Closed', 'Cancelled')),
  supplier_ticket_ref text,
  opened_at date not null default current_date,
  due_at date,
  closed_at date,
  resolution_notes text,
  cost numeric(12,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.printer_meter_readings (
  id uuid primary key default gen_random_uuid(),
  printer_id uuid not null references public.printers(id) on delete cascade,
  reading integer not null check (reading >= 0),
  reading_at date not null default current_date,
  captured_by_contact_id uuid references public.contacts(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists printers_status_idx on public.printers(status);
create index if not exists printers_location_id_idx on public.printers(location_id);
create index if not exists printers_department_id_idx on public.printers(department_id);
create index if not exists printer_toner_orders_printer_id_idx on public.printer_toner_orders(printer_id);
create index if not exists printer_paper_orders_printer_id_idx on public.printer_paper_orders(printer_id);
create index if not exists printer_tickets_printer_id_idx on public.printer_tickets(printer_id);
create index if not exists printer_meter_readings_printer_id_idx on public.printer_meter_readings(printer_id);

drop trigger if exists printers_set_updated_at on public.printers;
create trigger printers_set_updated_at
before update on public.printers
for each row execute function public.set_updated_at();

drop trigger if exists printer_toner_orders_set_updated_at on public.printer_toner_orders;
create trigger printer_toner_orders_set_updated_at
before update on public.printer_toner_orders
for each row execute function public.set_updated_at();

drop trigger if exists printer_paper_orders_set_updated_at on public.printer_paper_orders;
create trigger printer_paper_orders_set_updated_at
before update on public.printer_paper_orders
for each row execute function public.set_updated_at();

drop trigger if exists printer_tickets_set_updated_at on public.printer_tickets;
create trigger printer_tickets_set_updated_at
before update on public.printer_tickets
for each row execute function public.set_updated_at();

alter table public.printers enable row level security;
alter table public.printer_toner_orders enable row level security;
alter table public.printer_paper_orders enable row level security;
alter table public.printer_tickets enable row level security;
alter table public.printer_meter_readings enable row level security;

create policy "Authenticated users can read printers"
on public.printers for select
using (auth.uid() is not null);

create policy "Admins can manage printers"
on public.printers for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can read toner orders"
on public.printer_toner_orders for select
using (auth.uid() is not null);

create policy "Admins can manage toner orders"
on public.printer_toner_orders for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can read paper orders"
on public.printer_paper_orders for select
using (auth.uid() is not null);

create policy "Admins can manage paper orders"
on public.printer_paper_orders for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can read printer tickets"
on public.printer_tickets for select
using (auth.uid() is not null);

create policy "Admins can manage printer tickets"
on public.printer_tickets for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can read meter readings"
on public.printer_meter_readings for select
using (auth.uid() is not null);

create policy "Admins can manage meter readings"
on public.printer_meter_readings for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
