-- Tasks module: external_contacts, tasks, task_updates, task_follow_ups

create table if not exists public.external_contacts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  company text,
  email text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  task_code integer generated by default as identity unique not null,
  title text not null,
  status text not null default 'Intel'
    check (status in ('Intel', 'Briefed', 'Active Ops', 'Re-Routed', 'Standby', 'Neutralized', 'Retired')),
  status_reason text,
  status_changed_at timestamptz not null default now(),
  priority text not null default 'Standard'
    check (priority in ('Cold', 'Standard', 'Priority', 'Hot')),
  category text
    check (category in ('IT', 'Development', 'Data', 'Automation', 'Presentation', 'Admin', 'General')),
  source text
    check (source in ('Walk-in', 'Email', 'Meeting', 'WhatsApp', 'Call')),
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists public.task_updates (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.task_follow_ups (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  contact_id uuid references public.contacts(id) on delete set null,
  external_contact_id uuid references public.external_contacts(id) on delete set null,
  due_date date not null,
  note text,
  is_done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tasks_status_idx on public.tasks(status);
create index if not exists tasks_priority_idx on public.tasks(priority);
create index if not exists tasks_archived_at_idx on public.tasks(archived_at);
create index if not exists task_updates_task_id_idx on public.task_updates(task_id);
create index if not exists task_follow_ups_task_id_idx on public.task_follow_ups(task_id);
create index if not exists task_follow_ups_contact_id_idx on public.task_follow_ups(contact_id);
create index if not exists task_follow_ups_external_contact_id_idx on public.task_follow_ups(external_contact_id);

drop trigger if exists external_contacts_set_updated_at on public.external_contacts;
create trigger external_contacts_set_updated_at
before update on public.external_contacts
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

drop trigger if exists task_follow_ups_set_updated_at on public.task_follow_ups;
create trigger task_follow_ups_set_updated_at
before update on public.task_follow_ups
for each row execute function public.set_updated_at();

alter table public.external_contacts enable row level security;
alter table public.tasks enable row level security;
alter table public.task_updates enable row level security;
alter table public.task_follow_ups enable row level security;

create policy "Authenticated users can read external contacts"
on public.external_contacts for select
using (auth.uid() is not null);

create policy "Admins can manage external contacts"
on public.external_contacts for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can read tasks"
on public.tasks for select
using (auth.uid() is not null);

create policy "Admins can manage tasks"
on public.tasks for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can read task updates"
on public.task_updates for select
using (auth.uid() is not null);

create policy "Admins can manage task updates"
on public.task_updates for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can read task follow-ups"
on public.task_follow_ups for select
using (auth.uid() is not null);

create policy "Admins can manage task follow-ups"
on public.task_follow_ups for all
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
